// <auto-generated />
using System;
using FireSaverApi.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FireSaverApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211016101434_Route point entity  added")]
    partial class Routepointentityadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FireSaverApi.DataContext.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MapPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("WorldPositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapPositionId");

                    b.HasIndex("WorldPositionId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("FireSaverApi.DataContext.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longtitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("FireSaverApi.DataContext.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParentPointId")
                        .HasColumnType("int");

                    b.Property<int?>("PointPostionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentPointId");

                    b.HasIndex("PointPostionId");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("FireSaverApi.DataContext.Point", b =>
                {
                    b.HasOne("FireSaverApi.DataContext.Position", "MapPosition")
                        .WithMany()
                        .HasForeignKey("MapPositionId");

                    b.HasOne("FireSaverApi.DataContext.Position", "WorldPosition")
                        .WithMany()
                        .HasForeignKey("WorldPositionId");

                    b.Navigation("MapPosition");

                    b.Navigation("WorldPosition");
                });

            modelBuilder.Entity("FireSaverApi.DataContext.RoutePoint", b =>
                {
                    b.HasOne("FireSaverApi.DataContext.RoutePoint", "ParentPoint")
                        .WithMany("ChildrenPoints")
                        .HasForeignKey("ParentPointId");

                    b.HasOne("FireSaverApi.DataContext.Position", "PointPostion")
                        .WithMany()
                        .HasForeignKey("PointPostionId");

                    b.Navigation("ParentPoint");

                    b.Navigation("PointPostion");
                });

            modelBuilder.Entity("FireSaverApi.DataContext.RoutePoint", b =>
                {
                    b.Navigation("ChildrenPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
