//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSaverMobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireSaverMobile.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string BirthdayTitle {
            get {
                return ResourceManager.GetString("BirthdayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block point.
        /// </summary>
        internal static string BlockPoint {
            get {
                return ResourceManager.GetString("BlockPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building data.
        /// </summary>
        internal static string BuildingData {
            get {
                return ResourceManager.GetString("BuildingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center map.
        /// </summary>
        internal static string Centermap {
            get {
                return ResourceManager.GetString("Centermap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose lanuage.
        /// </summary>
        internal static string ChangeLanuage {
            get {
                return ResourceManager.GetString("ChangeLanuage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment description: .
        /// </summary>
        internal static string CompartmentDescribtion {
            get {
                return ResourceManager.GetString("CompartmentDescribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment name:.
        /// </summary>
        internal static string CompartmentName {
            get {
                return ResourceManager.GetString("CompartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Room.
        /// </summary>
        internal static string CurrentRoom {
            get {
                return ResourceManager.GetString("CurrentRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish test.
        /// </summary>
        internal static string FinishTest {
            get {
                return ResourceManager.GetString("FinishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment #{0} scale points.
        /// </summary>
        internal static string FloorTitle {
            get {
                return ResourceManager.GetString("FloorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as guest.
        /// </summary>
        internal static string GuestBtn {
            get {
                return ResourceManager.GetString("GuestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireSaver.
        /// </summary>
        internal static string HomeLogo {
            get {
                return ResourceManager.GetString("HomeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutBtn {
            get {
                return ResourceManager.GetString("LogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enetr your mail.
        /// </summary>
        internal static string MailTitle {
            get {
                return ResourceManager.GetString("MailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email format.
        /// </summary>
        internal static string MailValidationMessage {
            get {
                return ResourceManager.GetString("MailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your name....
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your name:.
        /// </summary>
        internal static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Room.
        /// </summary>
        internal static string NextCompartment {
            get {
                return ResourceManager.GetString("NextCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next point.
        /// </summary>
        internal static string NextPoint {
            get {
                return ResourceManager.GetString("NextPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Question.
        /// </summary>
        internal static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string PassCheckBox {
            get {
                return ResourceManager.GetString("PassCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enetr your pass.
        /// </summary>
        internal static string PassTitle {
            get {
                return ResourceManager.GetString("PassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email format.
        /// </summary>
        internal static string PassValidationMessage {
            get {
                return ResourceManager.GetString("PassValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your patronymic....
        /// </summary>
        internal static string PatronymicPlaceholder {
            get {
                return ResourceManager.GetString("PatronymicPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your patronymic:.
        /// </summary>
        internal static string PatronymicTitle {
            get {
                return ResourceManager.GetString("PatronymicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter 10 digits.
        /// </summary>
        internal static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your telephone number:.
        /// </summary>
        internal static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous point.
        /// </summary>
        internal static string PrevPont {
            get {
                return ResourceManager.GetString("PrevPont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Question.
        /// </summary>
        internal static string PrevQuestion {
            get {
                return ResourceManager.GetString("PrevQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible users:.
        /// </summary>
        internal static string ResponsibleUsers {
            get {
                return ResourceManager.GetString("ResponsibleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See plan.
        /// </summary>
        internal static string SeePlan {
            get {
                return ResourceManager.GetString("SeePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See rooms.
        /// </summary>
        internal static string SeeRooms {
            get {
                return ResourceManager.GetString("SeeRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        internal static string Shelter {
            get {
                return ResourceManager.GetString("Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your surname....
        /// </summary>
        internal static string SurnamePlaceholder {
            get {
                return ResourceManager.GetString("SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your surname:.
        /// </summary>
        internal static string SurnameTitle {
            get {
                return ResourceManager.GetString("SurnameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync position.
        /// </summary>
        internal static string SyncPos {
            get {
                return ResourceManager.GetString("SyncPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test question {0}/{1}.
        /// </summary>
        internal static string TestCaption {
            get {
                return ResourceManager.GetString("TestCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info.
        /// </summary>
        internal static string UpdateBtnTitle {
            get {
                return ResourceManager.GetString("UpdateBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected pos.
        /// </summary>
        internal static string UpdateSelectedPos {
            get {
                return ResourceManager.GetString("UpdateSelectedPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid value.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
